[pytest]
addopts = -v -s --headed --slowmo=500 --reruns 2

# Pytest internally turns your multi-line into this exact command line query:
# pytest --headed --browser=chromium --video=on --screenshot=on --tracing=on